"""Add size_type and size_combination_data to sizes table

Revision ID: 1bd31889f287
Revises: 88095ac3ef4f
Create Date: 2025-06-29 04:15:42.374839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bd31889f287'
down_revision: Union[str, Sequence[str], None] = '88095ac3ef4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sizes', sa.Column('size_type', sa.String(), nullable=True))
    op.add_column('sizes', sa.Column('size_combination_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sizes', 'size_combination_data')
    op.drop_column('sizes', 'size_type')
    # ### end Alembic commands ###
