"""Add file_hash and file_size to images table

Revision ID: 88095ac3ef4f
Revises: a37ac83e0ca0
Create Date: 2025-06-29 03:19:37.629591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88095ac3ef4f'
down_revision: Union[str, Sequence[str], None] = 'a37ac83e0ca0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('file_hash', sa.String(), nullable=True))
    op.add_column('images', sa.Column('file_size', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_images_file_hash'), 'images', ['file_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_images_file_hash'), table_name='images')
    op.drop_column('images', 'file_size')
    op.drop_column('images', 'file_hash')
    # ### end Alembic commands ###
