"""add_image_processing_fields_to_message_templates

Revision ID: 893f1fabea54
Revises: db76e4404371
Create Date: 2025-07-31 19:18:24.673403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '893f1fabea54'
down_revision: Union[str, Sequence[str], None] = 'db76e4404371'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Only add the new columns to message_templates table
    op.add_column('message_templates', sa.Column('combine_images', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('message_templates', sa.Column('optimize_images', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.add_column('message_templates', sa.Column('max_file_size_kb', sa.Integer(), nullable=False, server_default=sa.text('500')))
    op.add_column('message_templates', sa.Column('max_width', sa.Integer(), nullable=False, server_default=sa.text('1920')))
    op.add_column('message_templates', sa.Column('max_height', sa.Integer(), nullable=False, server_default=sa.text('1080')))
    op.add_column('message_templates', sa.Column('compression_quality', sa.Integer(), nullable=False, server_default=sa.text('80')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message_templates', 'compression_quality')
    op.drop_column('message_templates', 'max_height')
    op.drop_column('message_templates', 'max_width')
    op.drop_column('message_templates', 'max_file_size_kb')
    op.drop_column('message_templates', 'optimize_images')
    op.drop_column('message_templates', 'combine_images')
    # ### end Alembic commands ###