"""add_telegram_channels_and_posts_tables

Revision ID: 94f0296b0c17
Revises: 4637abeabe3f
Create Date: 2025-06-27 11:42:44.388533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94f0296b0c17'
down_revision: Union[str, Sequence[str], None] = '4637abeabe3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('chat_id', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('auto_post', sa.Boolean(), nullable=False),
    sa.Column('send_photos', sa.Boolean(), nullable=False),
    sa.Column('disable_web_page_preview', sa.Boolean(), nullable=False),
    sa.Column('disable_notification', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['message_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telegram_channels_chat_id'), 'telegram_channels', ['chat_id'], unique=True)
    op.create_index(op.f('ix_telegram_channels_deleted_at'), 'telegram_channels', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_telegram_channels_id'), 'telegram_channels', ['id'], unique=False)
    op.create_index(op.f('ix_telegram_channels_name'), 'telegram_channels', ['name'], unique=False)
    op.create_table('telegram_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('rendered_content', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['telegram_channels.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['message_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telegram_posts_id'), 'telegram_posts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telegram_posts_id'), table_name='telegram_posts')
    op.drop_table('telegram_posts')
    op.drop_index(op.f('ix_telegram_channels_name'), table_name='telegram_channels')
    op.drop_index(op.f('ix_telegram_channels_id'), table_name='telegram_channels')
    op.drop_index(op.f('ix_telegram_channels_deleted_at'), table_name='telegram_channels')
    op.drop_index(op.f('ix_telegram_channels_chat_id'), table_name='telegram_channels')
    op.drop_table('telegram_channels')
    # ### end Alembic commands ###
