"""add_message_templates_table

Revision ID: c3810c664928
Revises: 7539a7e5c9f5
Create Date: 2025-06-27 11:16:38.633809

"""
from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = 'c3810c664928'
down_revision: Union[str, Sequence[str], None] = '7539a7e5c9f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
