"""Initial migration

Revision ID: d7bf728a2f59
Revises: 
Create Date: 2025-06-25 22:38:09.225412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'd7bf728a2f59'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('product_url', sa.String(), nullable=False),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.Column('sku', sa.String(), nullable=True),
                    sa.Column('price', sa.Float(), nullable=True),
                    sa.Column('currency', sa.String(), nullable=True),
                    sa.Column('availability', sa.String(), nullable=True),
                    sa.Column('color', sa.String(), nullable=True),
                    sa.Column('composition', sa.String(), nullable=True),
                    sa.Column('item', sa.String(), nullable=True),
                    sa.Column('comment', sa.String(), nullable=True),
                    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
                    sa.Column('telegram_posted_at', sa.DateTime(timezone=True), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.CheckConstraint('price IS NULL OR price >= 0', name='ck_products_price_positive'),
                    sa.CheckConstraint("product_url LIKE 'http://%' OR product_url LIKE 'https://%'", name='ck_products_url_format')
                    )
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_index(op.f('ix_products_product_url'), 'products', ['product_url'], unique=True)
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=True)
    # Performance indexes
    op.create_index('ix_products_created_at_price', 'products', ['created_at', 'price'])
    op.create_index('ix_products_availability_price', 'products', ['availability', 'price'])
    op.create_index('ix_products_telegram_posted_at', 'products', ['telegram_posted_at'])
    
    op.create_table('images',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('url', sa.String(), nullable=False),
                    sa.Column('product_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('url')
                    )
    op.create_index(op.f('ix_images_id'), 'images', ['id'], unique=False)
    op.create_index('ix_images_product_id_url', 'images', ['product_id', 'url'])
    
    op.create_table('sizes',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('product_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.CheckConstraint("LENGTH(TRIM(name)) > 0", name='ck_sizes_name_not_empty')
                    )
    op.create_index(op.f('ix_sizes_id'), 'sizes', ['id'], unique=False)
    op.create_index('ix_sizes_product_id_name', 'sizes', ['product_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sizes_product_id_name', table_name='sizes')
    op.drop_index(op.f('ix_sizes_id'), table_name='sizes')
    op.drop_table('sizes')
    op.drop_index('ix_images_product_id_url', table_name='images')
    op.drop_index(op.f('ix_images_id'), table_name='images')
    op.drop_table('images')
    op.drop_index('ix_products_telegram_posted_at', table_name='products')
    op.drop_index('ix_products_availability_price', table_name='products')
    op.drop_index('ix_products_created_at_price', table_name='products')
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.drop_index(op.f('ix_products_product_url'), table_name='products')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
